### ISSUE TITLE
ImportError: cannot import name SkipCache

### ISSUE THREAD

**Issue by centaur1** [swizzler/swizzler#8]
For python 2 (tried it on Ubuntu 14.04.x LTS and 16.04.1 LTS), python versions 2.7.12 and 2.7.6:  Anyone else see this?
Traceback (most recent call last):
  File "swizzler.py", line 3, in <module>
    from twister import Twister
  File "/home/ubuntu/swizzler/twister.py", line 3, in <module>
    from functioncache import functioncache,SkipCache
ImportError: cannot import name SkipCache

**Comment by centaur1** [comment]
It appears there is a module name conflict with functioncache, pulling from the dist-packages vs this install:

```
Python 2.7.12 (default, Jul  1 2016, 15:12:24) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import functioncache
>>> print(function cache
<module 'functioncache' from '/usr/local/lib/python2.7/dist-packages/functioncache-0.89-py2.7.egg/functioncache/__init__.pyc'>

```

My Q&D solution was to make a sym-link into my swizzler directory for functioncache.py from the dependencies directory so that it loaded first:
e.g.:
ln -s /PATH-TO-SWIZZLER/swizzler/dependencies/functioncache/functioncache/**init**.py functioncache.py
(note there are 2 underscores before and after init although they appear not to be showing up above)
